dist: trusty
language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
    - PHPUNIT_VERSION=~8 STABILITY=stable
    - PHPUNIT_VERSION=~9 STABILITY=dev

matrix:
  include:
    - php: 7.2
  allow_failures:
    - env: PHPUNIT_VERSION=~9 STABILITY=dev
    - php: nightly
    fast_finish: true

before_script:
  - travis_retry composer self-update
  - composer config minimum-stability ${STABILITY}
  - travis_retry composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update
  - travis_retry composer update --prefer-stable --prefer-lowest --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

#after_script:
#    - wget https://scrutinizer-ci.com/ocular.phar
#    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
